syntax on
set noerrorbells "no sound effects
set tabstop=4 softtabstop=4 "how many spaces a tab should use
set shiftwidth=4 
set expandtab
set wildmenu 
set smartindent
set rnu relativenumber "relative line number
set nowrap
set smartcase 
set noswapfile "no swap file (vim creates them by default) 
set nobackup "no backup file
set undodir=~/.nvim/undodir
set undofile
set cursorline
set incsearch
set formatoptions-=cro
set background=dark

call plug#begin("~/.vim/plugged")
" add plugins here
Plug 'ps173/dadara' 
Plug 'gruvbox-community/gruvbox'
Plug 'liuchengxu/space-vim-dark'
Plug 'dracula/vim', { 'as': 'dracula' }

"CSS properties and color selector
Plug 'KabbAmine/vCoolor.vim'
Plug 'lilydjwg/colorizer'

" File explorer
Plug 'scrooloose/nerdtree'
Plug 'ryanoasis/vim-devicons'

"Intellisense and code completion with syntax highlighting
Plug 'vim-jp/vim-java' 
Plug 'neoclide/coc.nvim', {'branch': 'release'}
let g:coc_global_extensions = ['coc-css', 'coc-html', 'coc-json', 'coc-tsserver', 'coc-java', 'coc-pyright', 'coc-go', 'coc-rust-analyzer', 'coc-flutter', 'coc-kotlin', 'coc-phpls']
Plug 'sheerun/vim-polyglot'
let g:polyglot_disabled = ['markdown']
Plug 'plasticboy/vim-markdown'  " Markdown plugin
Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }, 'for': ['markdown', 'vim-plug']}
Plug 'preservim/nerdcommenter'
      
" Airline
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

" LiveServer
Plug 'https://github.com/wolandark/vim-live-server.git'

" Golang
Plug 'fatih/vim-go', { 'do': ':GoInstallBinaries' }
" Completion tool for golang
Plug 'nsf/gocode', { 'tag': 'v.20150303', 'rtp': 'vim' }
" Golang completion tool for deoplete
Plug 'zchee/deoplete-go', { 'do': 'make'}

call plug#end()

colorscheme space-vim-dark

"NERD TREE AND ICONS
let g:NERDTreeShowHidden = 1
let g:NERDTreeMinimalUI = 0
let g:NERDTreeIgnore = ['node_modules']
let NERDTreeStatusline='NERDTree'
"Automaticaly close nvim if NERDTree is only thing left open
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
"File explorer plugin
"map <C-b> :NERDTreeToggle<CR>
nnoremap <silent> <C-b> :NERDTreeToggle<CR>
"nerd commenter
noremap <leader>c :NERDCommenterComment<CR>
"use alt+hjkl to move between split/vsplit panels
tnoremap <A-h> <C-\><C-n><C-w>h
tnoremap <A-j> <C-\><C-n><C-w>j
tnoremap <A-k> <C-\><C-n><C-w>k
tnoremap <A-l> <C-\><C-n><C-w>l
nnoremap <A-h> <C-w>h
nnoremap <A-j> <C-w>j
nnoremap <A-k> <C-w>k
nnoremap <A-l> <C-w>l
" mapping escape to ctrl c
map <Esc><C-c> <CR>
inoremap jk <Esc>
inoremap kj <Esc>
" Make Enter accept the autocomplete suggestion.
inoremap <silent><expr> <CR> pumvisible() ? coc#_select_confirm() : "\<CR>"
" alternater way to save
nnoremap <silent> <C-s> :w<CR>
nnoremap <silent> <C-Down>    :resize -2<CR>
nnoremap <silent> <C-Up>  :resize +2<CR>
nnoremap <silent> <C-Left>  :vertical resize -2<CR>
nnoremap <silent> <C-Right> :vertical resize +2<CR>

" configuration markdown
let g:mkdp_auto_start = 0           " Do not start automatically
let g:mkdp_auto_close = 1           " Close when exiting vim
let g:mkdp_refresh_slow = 0         " Instant update
let g:mkdp_browser = 'chromium'     " Use browser (o 'chrome', 'brave', 'chromium')
let g:mkdp_theme = 'dark'           " Themes ('light', 'dark')
